name: Go CI
on:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: check
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go-version:
          - '1.18'
          - '1.19'
          - '1.20'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run Go CI
        uses: ghacts/go@main
        with:
          go-version: ${{ matrix.go-version }}
          artifact-name: "verse-${{ matrix.os }}-go-${{ matrix.go-version }}"
