name: test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  test:
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20' ]
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

